server:
  port: 0

spring:
  application:
    name: max-account
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/max}
    username: ${POSTGRES_USER:max}
    password: ${POSTGRES_PASSWORD:max}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: account
  jpa:
    properties:
      hibernate:
        default_schema: account
  redis:
    host: redis
    port: 6379

management:
  endpoints:
    web:
      base-path: /accounts/actuator
      exposure:
        include: ['*', 'prometheus']

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVERY_HOST:max-discovery}:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /accounts/v3/api-docs
  swagger-ui:
    path: /accounts/swagger-ui
