spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/max}
    username: ${DATABASE_USERNAME:max}
    password: ${DATABASE_PASSWORD:max}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: account
  jpa:
    properties:
      hibernate:
        default_schema: account